### ISSUE TITLE
path/input folder should be the same?

### ISSUE THREAD

**Issue by dkriegner** [dkriegner/micro-flakes#20]
It is awkward that as a user I have to generate an input folder. The call of the script below is expected to work, but the script looks for the image in an unexpected path. Lets reconsider that so that its more intutitive for the user.

In my opinion the input image should be looked for in the path I specify with the` -p` option

```
(python-venv) 
# micro-flakes on git:main o python-venv [18:39:12] 
$ ls Samples_for_testing 
black2.jpg  black3.jpg  black.png  CACHE  calib.jpg  calibration2.jpg  calibration.jpg  input  newDF.jpg  output
(python-venv) 
# micro-flakes on git:main o python-venv [18:39:16] 
$ flakes-detector -p . -n Samples_for_testing/calibration.jpg -o False -m 42.4 -s 40
Traceback (most recent call last):
  File "/home/dk/tmp/python-venv/bin/flakes-detector", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/dk/cesnet/devel/micro-flakes/Detector/main.py", line 104, in main
    figure1 = ImageCrawler(path, name, more_output, min_size, sensitivity, calibration)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dk/cesnet/devel/micro-flakes/Detector/find_objects.py", line 43, in __init__
    self.orig_photo, self.output = self._load_image()
                                   ^^^^^^^^^^^^^^^^^^
  File "/home/dk/cesnet/devel/micro-flakes/Detector/find_objects.py", line 93, in _load_image
    orig_photo = Image.open(f"{self.path}/input/{self.name}")  # open the original photo
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dk/tmp/python-venv/lib/python3.11/site-packages/PIL/Image.py", line 3243, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './input/Samples_for_testing/calibration.jpg'
(python-venv) 
```

**Comment by ji-ze** [comment]
It has been here since an old version. It isn't necessary. I removed it.
